server:
  port: 19999

spring:
  application:
    name: bronze-gateway

gateway:
  port: 9999
  backendResponseTimeoutMs: 6000 # 后端响应超时时间
  clientWriteTimeoutMs: 6000 # 客户端写入超时时间
  connectTimeoutMs: 6000 # 连接超时时间
  routes:
    - id: user-service # 服务名称，每个服务唯一
      path: /user/ # 服务访问路径，注意，前后都要斜杠，不能有*号
      instances:
        - serviceId: user-service-1 # 服务实例名称，同一个服务下，不同实例，serviceId要求唯一
          url: http://localhost:8081 # 服务地址，到端口一层即可
          weight: 1 # 权重，目前系统默认轮询策略
          healthy: true # 服务健康状态，预留，目前默认为true
    - id: jm-cloud-gw
      path: /jm-cloud-gw/ # 注意，前后都要斜杠，不能有*号
      loadBalancerType: weightedLoadBalancer # 负载均衡类型 roundRobinLoadBalancer轮询 / WeightedLoadBalancer权重
      instances:
        - serviceId: jm-cloud-gw-1
          url: http://192.168.1.240:23500
          weight: 1
          healthy: true
        - serviceId: jm-cloud-gw-2
          url: http://192.168.1.111:23500
          weight: 1
          healthy: true
#  filters:
#    - name: AuthFilter  # 与@Component("AuthFilter")匹配
#      order: -100
#    - name: RateLimitFilter  # 与@Component("RateLimitFilter")匹配
#      order: -90
#      args:
#        permitsPerSecond: "1000"

#熔断配置
  resilience:
    failureRateThreshold: 50 # 失败率阈值百分比
    slowCallRateThreshold: 50 # 慢调用率阈值百分比
    slowCallDurationThreshold: 10 # 慢调用持续时间阈值
    waitDurationInOpenState: 60 # 熔断器开启状态持续时间
    permittedNumberOfCallsInHalfOpenState: 5 # 半开状态允许的调用次数
    minimumNumberOfCalls: 2 # 计算失败率所需的最小调用次数
    slidingWindowSize: 5 # 滑动窗口大小
