server:
  port: 19999

spring:
  application:
    name: bronze-gateway

gateway:
  port: 9999
  backendResponseTimeoutMs: 6000
  clientWriteTimeoutMs: 6000
  routes:
    - id: user-service
      path: /user/
      uri: http://localhost:8081
      order: 0
      instances:
        - serviceId: user-service
          url: http://localhost:8081
          weight: 1
          healthy: true
    - id: jm-cloud-gw
      path: /jm-cloud-gw/ # 注意，前后都要斜杠，不能有*号
      uri: http://192.168.1.240:23500
      order: 0
      instances:
        - serviceId: jm-cloud-gw
          url: http://192.168.1.240:23500
          weight: 1
          healthy: true
        - serviceId: jm-cloud-gw
          url: http://192.168.1.240:23500
          weight: 1
          healthy: true
  filters:
#    - name: AuthFilter  # 与@Component("AuthFilter")匹配
#      order: -100
    - name: RateLimitFilter  # 与@Component("RateLimitFilter")匹配
      order: -90
      args:
        permitsPerSecond: "1000"
